# Generated by Django 5.2 on 2025-05-02 19:24

from django.db import migrations
from django.utils import timezone

def add_snowboards(apps, schema_editor):
    # Get the models
    Snowboard = apps.get_model('rentals', 'Snowboard')
    
    # Create snowboard instances - add your actual data here
    Snowboard.objects.create(
        name='Burton Feelgood',
        description='Precise, powerful all-mountain womens board.',
        rental_price=100.00,
        quantity_available=10,
        image='snowboards/Burton_FeelGood.png'
    )
    
    Snowboard.objects.create(
        name='Burton Blossom',
        description='Cambered twin for park and pop',
        rental_price=100.00,
        quantity_available=10,
        image='snowboards/Burton_Blossom.png'
    )

    Snowboard.objects.create(
        name='Bataleon Spirit',
        description='Soft, forgiving board for beginners',
        rental_price=100.00,
        quantity_available=10,
        image='snowboards/Bataleon_Spirit.png'
    )
    
    Snowboard.objects.create(
        name='Bataleon Goliath',
        description='Balanced all-mountain twin',
        rental_price=100.00,
        quantity_available=10,
        image='snowboards/Bataleon_Goliath.png'
    )

    Snowboard.objects.create(
        name='Bataleon Evil Twin',
        description='Freestyle twin with pop and control',
        rental_price=100.00,
        quantity_available=10,
        image='snowboards/Bataleon_Evil_Twin.png'
    )

    Snowboard.objects.create(
        name='K2 Passport',
        description='Stable, versatile board for any terrain',
        rental_price=100.00,
        quantity_available=10,
        image='snowboards/K2_Passport.png'
    )

    # Add additional snowboards as needed...

def remove_snowboards(apps, schema_editor):
    # For reversing the migration
    Snowboard = apps.get_model('rentals', 'Snowboard')
    Snowboard.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('rentals', '0001_initial'),  # Make sure this matches your latest migration
    ]

    operations = [
        migrations.RunPython(add_snowboards, remove_snowboards),
    ]